name: 'Vulnerabilities check'
description: 'Check you project for vulnerabilities'
inputs:
  file:
    description: 'The project`s file, pom.xml as an example'
    default: 'pom.xml' # default value for the action development
    required: true
  organisation:
    description: 'The organisation name'
outputs:
  report:
    description: 'A file with a report in HTML/JSON? format'
runs:
  using: 'node12'
  main: 'dist/index.js'
